#!/bin/bash
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Purpose:  This script will allow you to save your Docker containers locally

. /usr/sbin/so-elastic-common

echo
echo
echo "This script will allow you to save your Security Onion docker containers locally."
echo
echo "Please enter the file path where you would like to save the images."
read -e imagepath

# No output from docker save so no sense in asking to save log
echo "This may take a while."
for image in $(docker images | grep -E "$DOCKERHUB|registry" | awk '{ print $1 }'); do
    imagename=$(echo $image | sed 's/\:/_/g;s/\//_/g')
    echo "Saving $image to $imagepath/$imagename"
    docker save $image -o $imagepath/$imagename
done

echo "Complete!"
